import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import QueryProvider from '@/components/providers/query-provider'
import AuthSession from '@/components/providers/session-provider'
import Header from "@/components/header";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    return (
    <html lang="en">
      <body className={inter.className}>
      <AuthSession>
      <QueryProvider>
          <Header></Header>
        {children}
      </QueryProvider>
      </AuthSession>

      </body>
    </html>
  )
}
